# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Akskrotate < Formula
  desc "Rotate your aws access key / secret key with confidence"
  homepage "https://github.com/easytocloud/akskrotate"
  url "https://github.com/easytocloud/akskrotate/archive/refs/tags/v0.2.6.tar.gz"
  sha256 "0c87708f28f854a9cea3bd9a7a12b9c1006ff88d1b3bd0d1bce53dfe6921bcd5"
  license "MIT"

  def install
    bin.install "distribution/bin/akskrotate" => "akskrotate"
  end

  test do
    assert_match("Please set AWS_PROFILE before calling akskrotate", shell_output("unset AWS_PROFILE ; akskrotate 2>&1", 1))
  end
end
