# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Akskrotate < Formula
  desc "Rotate your aws access key / secret key with confidence"
  homepage "https://github.com/easytocloud/akskrotate"
  url "https://github.com/easytocloud/akskrotate/archive/refs/tags/v0.3.0.tar.gz"
  sha256 "13f159a1ae470c3c031899ebf3ddb55d898ef72e94b2072d4d11435526d374e5"
  license "MIT"

  def install
    bin.install "distribution/bin/akskrotate" => "akskrotate"
  end

  test do
    assert_match("Please set AWS_PROFILE before calling akskrotate", shell_output("unset AWS_PROFILE ; akskrotate 2>&1", 1))
  end
end
