# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class AwsUtils < Formula
  desc "Aws utilities"
  homepage "https://github.com/easytocloud/aws-utils"
  url "https://github.com/easytocloud/aws-utils/archive/refs/tags/v0.6.4.tar.gz"
  sha256 "93ab0a3c6c2c36fe0b499e1dad215f01d4a89f24fb265f77731700fe433106e1"
  license "MIT"

  def install
    bin.install "distribution/bin/ccclone"
bin.install "distribution/bin/cclist"
bin.install "distribution/bin/ccinit"
bash_completion.install "distribution/completions/ccclone-completion.bash"
zsh_completion.install "distribution/completions/_ccclone"
  end
end
