# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class AwsUtils < Formula
  desc "Aws utilities"
  homepage "https://github.com/easytocloud/aws-utils"
  url "https://github.com/easytocloud/aws-utils/archive/refs/tags/v0.3.1.tar.gz"
  sha256 "adbb4ae70cea857b29b5b0d7b483973a3a939eebb666e782d033cd20ce7109e5"
  license "MIT"

  def install
    bin.install "distribution/bin/ccclone"
bin.install "distribution/bin/cclist"
bin.install "distribution/bin/ccinit"
bin.install "distribution/bin/release"
  end
end
