# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class AwsProfileOrganizer < Formula
  desc "Organize your aws profile"
  homepage "https://github.com/easytocloud/aws-profile-organizer"
  url "https://github.com/easytocloud/aws-profile-organizer/archive/refs/tags/v0.3.11.tar.gz"
  sha256 "390888316c05c3fe96c07e35a264fd92313618dad5316c330e622f4c7de71473"
  license "MIT"

  depends_on "easytocloud/tap/zsh_functions"

  def install
    bin.install "distribution/bin/aws-profile-organizer-setup"
bin.install "distribution/bin/aws-profile-organizer-rc"
bin.install "distribution/bin/aws-profile-organizer-set-defaults"

zsh_function.install "distribution/functions/awsenv"
zsh_function.install "distribution/functions/awsprofile"
zsh_function.install "distribution/functions/awsmfa"
  end
end
