# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class AwsProfileOrganizer < Formula
  desc "Organize your aws profile"
  homepage "https://github.com/easytocloud/aws-profile-organizer"
  url "https://github.com/easytocloud/aws-profile-organizer/archive/v0.2.3.tar.gz"
  sha256 "1e96101c20643069b3ba2baa1ebfa886a7712cc4e0125913b75d4c873665ade2"
  license "MIT"

  depends_on "bash" => :build

  def install
    bin.install "distribution/bin/aws-profile-organizer-setup"
bin.install "distribution/bin/aws-profile-organizer-rc"
bin.install "distribution/bin/aws-profile-organizer-set-defaults"

zsh_function.install "distribution/functions/awsenv"
zsh_function.install "distribution/functions/awsprofile"
zsh_function.install "distribution/functions/awsmfa"

zsh_function.install "distribution/functions/_log"
zsh_function.install "distribution/functions/_error"
zsh_function.install "distribution/functions/_debug"
zsh_function.install "distribution/functions/_die"
  end
end
