# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class AwsUtils < Formula
  desc "Aws utilities"
  homepage "https://github.com/easytocloud/aws-utils"
  url "https://github.com/easytocloud/aws-utils/archive/refs/tags/v0.4.1.tar.gz"
  sha256 "ccaac5462b2dfacc8806cc790f018b45e7fedc56db1c7dafa6124322790badc0"
  license "MIT"

  def install
    bin.install "distribution/bin/ccclone"
bin.install "distribution/bin/cclist"
bin.install "distribution/bin/ccinit"
  end
end
