# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class CaUvx < Formula
  desc "Codeartifact wrapper for uvx/uv - seamlessly use aws codeartifact as a python pa"
  homepage "https://github.com/easytocloud/ca-uvx"
  url "https://github.com/easytocloud/ca-uvx/archive/refs/tags/v1.3.0.tar.gz"
  sha256 "bb94e587cfc8f89b8d74ed73f71d15b7ab280715f766136f86e34e6099bb3d22"
  license "MIT"

  def install
    bin.install "distribution/bin/ca-uvx" => "ca-uvx"
  end

  test do
    assert_match("ca-uvx", shell_output("ca-uvx --version"))
  end
end
