# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class CaUvx < Formula
  desc "Codeartifact wrapper for uvx/uv - seamlessly use aws codeartifact as a python pa"
  homepage "https://github.com/easytocloud/ca-uvx"
  url "https://github.com/easytocloud/ca-uvx/archive/refs/tags/v1.2.0.tar.gz"
  sha256 "cddce6acf7122559363e45c4a43707ae3c74fce2e89812bd6634dcec90c3105b"
  license "MIT"

  def install
    bin.install "distribution/bin/ca-uvx" => "ca-uvx"
  end

  test do
    assert_match("ca-uvx", shell_output("ca-uvx --version"))
  end
end
