# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class CaUvx < Formula
  desc "Codeartifact wrapper for uvx/uv - seamlessly use aws codeartifact as a python pa"
  homepage "https://github.com/easytocloud/ca-uvx"
  url "https://github.com/easytocloud/ca-uvx/archive/refs/tags/v1.1.1.tar.gz"
  sha256 "250b214d8e2e6356d27e572ca68f1fd04a090fb9d4807b86675f277c93dfacf5"
  license "MIT"

  def install
    bin.install "distribution/bin/ca-uvx" => "ca-uvx"
  end

  test do
    assert_match("ca-uvx", shell_output("ca-uvx --version"))
  end
end
