# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Cloudx < Formula
  desc "Tools to convert an amazon linux instance to a vscode backend"
  homepage "https://github.com/easytocloud/cloudX"
  url "https://github.com/easytocloud/cloudX/archive/v0.1.3.tar.gz"
  sha256 "62bc3f748a19331458ff817efa79d4142c19de6dc249cc9b0b343b3743e2c593"
  license "MIT"

  def install
    bin.install "distribution/bin/cloudX-proxy.sh"
  end
end
