# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Cloud9ToPowerVscodeBlog < Formula
  desc "Artifacts used in the blog post use aws cloud9 to power your visual studio code"
  homepage "https://github.com/easytocloud/cloud9-to-power-vscode-blog"
  url "https://github.com/easytocloud/cloud9-to-power-vscode-blog/archive/v0.3.1.tar.gz"
  sha256 "c5350889ca277b61ef97af57284d86dd83bee9182d468c26b450dae8e77f3fda"
  license "MIT-0"

  depends_on "bash" => :build

  def install
    bin.install "distribution/bin/aws-proxy.sh"
bin.install "distribution/bin/cloud9-mod.json"
  end
end
