# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Cloud9ToPowerVscodeBlog < Formula
  desc "Artifacts used in the blog post use aws cloud9 to power your visual studio code"
  homepage "https://github.com/easytocloud/cloud9-to-power-vscode-blog"
  url "https://github.com/easytocloud/cloud9-to-power-vscode-blog/archive/v0.1.4.tar.gz"
  sha256 "e4d966f1a327529bc20f0e97344cca45f05c17bd63befbf09daadfb9bf1be80f"
  license "MIT-0"

  depends_on "bash" => :build

  def install
    bin.install "distribution/bin/aws-proxy.sh"
bin.install "distribution/bin/cloud9-mod.json"
  end
end
