# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Cloudx < Formula
  desc "Tools to convert an amazon linux instance to a vscode backend"
  homepage "https://github.com/easytocloud/cloudX"
  url "https://github.com/easytocloud/cloudX/archive/v0.1.0.tar.gz"
  sha256 "c7a83c3e379e803775ba7454f957c2db26ade5a7e9630f190fcc0bd33a7abd33"
  license "MIT"

  def install
    bin.install "distribution/bin/cloudX-proxy.sh"
  end
end
