# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class CodeartifactUv < Formula
  desc "Automatically update uv config to use codeartifact"
  homepage "https://github.com/easytocloud/codeartifact-uv"
  url "https://github.com/easytocloud/codeartifact-uv/archive/refs/tags/v1.0.5.tar.gz"
  sha256 "bdc1d298dec40c4e6bb91a400591db9eaa5b200511e75c5e20ab973870f6b93e"
  license "MIT"

  def install
    bin.install "distribution/bin/sync-pip-to-uv"
  end

  test do
    system "#{bin}/sync-pip-to-uv", "help"
  end
end
