# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class CodeartifactUv < Formula
  desc "Automatically update uv config to use codeartifact"
  homepage "https://github.com/easytocloud/codeartifact-uv"
  url "https://github.com/easytocloud/codeartifact-uv/archive/refs/tags/v1.0.8.tar.gz"
  sha256 "9b13002a1362e33548cbcb685cae3280fd7c64d7d1bc5b31e71ee418692f8500"
  license "MIT"

  def install
    bin.install "distribution/bin/sync-pip-to-uv"
  end

  test do
    system "#{bin}/sync-pip-to-uv", "help"
  end
end
