# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class CodecommitUtils < Formula
  desc "Collection of command-line utilities to simplify working with aws codecommit r"
  homepage "https://github.com/easytocloud/codecommit-utils"
  url "https://github.com/easytocloud/codecommit-utils/archive/refs/tags/v0.6.5.tar.gz"
  sha256 "86c44a7933a4f51646bc4cee03c339791624a76f465d9247f856029e274ceb78"
  license "MIT"

  def install
    bin.install "distribution/bin/ccclone"
bin.install "distribution/bin/cclist"
bin.install "distribution/bin/ccinit"
bash_completion.install "distribution/completions/ccclone-completion.bash"
zsh_completion.install "distribution/completions/_ccclone"
  end
end
