# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class CodecommitUtils < Formula
  desc "Brings gh-style shorthand to aws codecommit repositories and pull requests"
  homepage "https://github.com/easytocloud/codecommit-utils"
  url "https://github.com/easytocloud/codecommit-utils/archive/refs/tags/v0.7.2.tar.gz"
  sha256 "73e8d1a8e736010126d65863c0408b1abc3440e52856d0ffda68b463ac71c857"
  license "MIT"

  def install
    bin.install "distribution/bin/cch"
bin.install "distribution/bin/ccclone"
bin.install "distribution/bin/cclist"
bin.install "distribution/bin/ccinit"
man1.install "distribution/man/cch.1"
man1.install "distribution/man/ccclone.1"
man1.install "distribution/man/cclist.1"
man1.install "distribution/man/ccinit.1"
bash_completion.install "distribution/completions/cch-completion.bash"
bash_completion.install "distribution/completions/ccclone-completion.bash"
bash_completion.install "distribution/completions/cclist-completion.bash"
zsh_completion.install "distribution/completions/_cch"
zsh_completion.install "distribution/completions/_ccclone"
zsh_completion.install "distribution/completions/_cclist"
  end

  test do
    assert_match "cch #{version}", shell_output("#{bin}/cch --version")
assert_match "Work with AWS CodeCommit repositories", shell_output("#{bin}/cch --help")
assert_predicate man1/"cch.1", :exist?
  end
end
