# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class CodeartifactUv < Formula
  desc "Automatically update uv config to use codeartifact"
  homepage "https://github.com/easytocloud/codeartifact-uv"
  url "https://github.com/easytocloud/codeartifact-uv/archive/refs/tags/v1.0.7.tar.gz"
  sha256 "be30eadaf010867e5a39c825ec9649c67666c3e155716dca324c0cc94ad2fda4"
  license "MIT"

  def install
    bin.install "distribution/bin/sync-pip-to-uv"
  end

  test do
    system "#{bin}/sync-pip-to-uv", "help"
  end
end
