# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class ForTools < Formula
  desc "Aws cli tools to iterate over multiple profiles, roles, users or aws organizatio"
  homepage "https://github.com/easytocloud/for-tools"
  url "https://github.com/easytocloud/for-tools/archive/v0.2.2.tar.gz"
  sha256 "2ea9e439aebfdb22f055ef107d33bca3dd2208d92f270cef844a7a1657ef3783"
  license "MIT"

  depends_on "bash" => :build
  depends_on "easytocloud/tap/zsh_functions"

  def install
    bin.install "distribution/bin/for-tools"
bin.install "distribution/bin/for-iamusers"
bin.install "distribution/bin/for-iamroles"
bin.install "distribution/bin/for-profiles"
bin.install "distribution/bin/for-org_accts"
bin.install "distribution/bin/ac2name"
bin.install "distribution/bin/name2ac"
  end
end
