# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Iamhere < Formula
  desc "Tag-based change security group to allow traffic from your current ip address"
  homepage "https://github.com/easytocloud/iamhere"
  url "https://github.com/easytocloud/iamhere/archive/v0.1.4.tar.gz"
  sha256 "c302549def204b8aabc2cb1f1316facecae664685477218f9be1df85e941cd7a"
  license "MIT"

  depends_on "bash" => :build

  def install
    bin.install "distribution/bin/iamhere"
  end
end
