# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Iamhere < Formula
  desc "Tag-based change security group to allow traffic from your current ip address"
  homepage "https://github.com/easytocloud/iamhere"
  url "https://github.com/easytocloud/iamhere/archive/v0.1.1.tar.gz"
  sha256 "5a30d1fdd01e676f62f850d6d0dcb391228c4dc10a50361ae121f8976d85274a"
  license "MIT"

  depends_on "bash" => :build

  def install
    bin.install "distribution/bin/iamhere"
  end
end
