# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Iamhere < Formula
  desc "Tag-based change security group to allow traffic from your current ip address"
  homepage "https://github.com/easytocloud/iamhere"
  url "https://github.com/easytocloud/iamhere/archive/v0.1.5.tar.gz"
  sha256 "d1843ac609e9715acec2fe28408979e73526560ecad56843ef0d5938c99e45aa"
  license "MIT"

  depends_on "bash" => :build

  def install
    bin.install "distribution/bin/iamhere"
  end
end
