# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LayoutUv < Formula
  desc "Direnv layout extension"
  homepage "https://github.com/easytocloud/layout_uv"
  url "https://github.com/easytocloud/layout_uv/archive/refs/tags/v1.2.0.tar.gz"
  sha256 "06c638429cc24eee4e1e6890ae8f00618b17dde4b0232fc32f911e7cbe4872c9"
  license "MIT"

  def install
    pkgshare.install "distribution/lib/layout_uv.sh"
bin.install "distribution/bin/install-layout-uv"
  end

  test do
    assert_predicate pkgshare/"layout_uv.sh", :exist?
  end
end
