# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LayoutUv < Formula
  desc "Direnv layout extension"
  homepage "https://github.com/easytocloud/layout_uv"
  url "https://github.com/easytocloud/layout_uv/archive/refs/tags/v1.0.2.tar.gz"
  sha256 "2faf071e39c4dc92098b3ebd13a6ac352e0700ebeca2b014fc72256a2a8404a4"
  license "MIT"

  def install
    pkgshare.install "distribution/lib/layout_uv.sh"
bin.install "distribution/bin/install-layout-uv"

direnv_lib = "#{Dir.home}/.config/direnv/lib"
FileUtils.mkdir_p(direnv_lib)
FileUtils.cp("#{pkgshare}/layout_uv.sh", "#{direnv_lib}/layout_uv.sh")
ohai "✓ layout_uv function installed to #{direnv_lib}/layout_uv.sh"
  end

  test do
    assert_predicate pkgshare/"layout_uv.sh", :exist?
  end
end
