# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LayoutUv < Formula
  desc "Direnv layout extension"
  homepage "https://github.com/easytocloud/layout_uv"
  url "https://github.com/easytocloud/layout_uv/archive/refs/tags/v1.1.0.tar.gz"
  sha256 "73c0664c4940db764300b5b61bdd65260c95e9765c0c747ab22bbc80e71a9c5c"
  license "MIT"

  def install
    pkgshare.install "distribution/lib/layout_uv.sh"
bin.install "distribution/bin/install-layout-uv"
  end

  test do
    assert_predicate pkgshare/"layout_uv.sh", :exist?
  end
end
