# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class MacLetterhead < Formula
  desc "Letterhead pdf as digital stationery: prints markdown without overprinting heade"
  homepage "https://github.com/easytocloud/Mac-letterhead"
  url "https://github.com/easytocloud/Mac-letterhead/archive/refs/tags/v0.24.0.tar.gz"
  sha256 "bc3867c00c1f51dac2ccf4ee8245ecc60715157ea30d011adf95eaf9aa25c3f7"
  license "MIT"

  depends_on "uv"

  def install
    bin.install "distribution/bin/mac-letterhead" => "mac-letterhead"
  end

  test do
    assert_match("mac-letterhead", shell_output("#{bin}/mac-letterhead --version"))
  end
end
