# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class MacLetterhead < Formula
  desc "Letterhead pdf as digital stationery: prints markdown without overprinting heade"
  homepage "https://github.com/easytocloud/Mac-letterhead"
  url "https://github.com/easytocloud/Mac-letterhead/archive/refs/tags/v0.20.1.tar.gz"
  sha256 "eefae5699d0633d7ff525b9c78d262403f88cef58fb7ab12f632bfd485b5628b"
  license "MIT"

  depends_on "uv"

  def install
    bin.install "distribution/bin/mac-letterhead" => "mac-letterhead"
  end

  test do
    assert_match("mac-letterhead", shell_output("#{bin}/mac-letterhead --version"))
  end
end
