# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class MacLetterhead < Formula
  desc "Letterhead pdf as digital stationery: prints markdown without overprinting heade"
  homepage "https://github.com/easytocloud/Mac-letterhead"
  url "https://github.com/easytocloud/Mac-letterhead/archive/refs/tags/v0.24.1.tar.gz"
  sha256 "bbdd5b4174556d88a2feeaa04dcd3afc937729dfde61953b9658cde715eefb95"
  license "MIT"

  depends_on "uv"

  def install
    bin.install "distribution/bin/mac-letterhead" => "mac-letterhead"
  end

  test do
    assert_match("mac-letterhead", shell_output("#{bin}/mac-letterhead --version"))
  end
end
