# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class OhMyEasytocloud < Formula
  desc "Upgrade oh-my-zsh agnoster theme with aws_env in prompt"
  homepage "https://github.com/easytocloud/oh-my-easytocloud"
  url "https://github.com/easytocloud/oh-my-easytocloud/archive/refs/tags/v0.2.17.tar.gz"
  sha256 "06bf3e5781b908425700c863ea14618658e6107c8dc2ddf2f71ebda000a0f5ed"
  license "MIT"

  def install
    (share/"oh-my-easytocloud/plugins/easytocloud").install Dir["plugins/easytocloud/*"]
(share/"oh-my-easytocloud/themes").install "themes/easytocloud.zsh-theme"
(share/"doc/oh-my-easytocloud").install "README.md"
  end

  test do
    system "test", "-d", share/"oh-my-easytocloud/plugins/easytocloud"
system "test", "-f", share/"oh-my-easytocloud/themes/easytocloud.zsh-theme"
  end
end
