# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Privpage < Formula
  desc "Aws pager masking privacy sensitive information"
  homepage "https://github.com/easytocloud/privpage"
  url "https://github.com/easytocloud/privpage/archive/v0.2.1.tar.gz"
  sha256 "316a32f42cc38b2464e0a6c85d30fafccb13e2b0fe6d977499ba65f0c7e41775"
  license "MIT"

  depends_on "bash" => :build

  def install
    bin.install "distribution/bin/privpage"
bin.install "distribution/bin/whoami"
  end
end
