# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Privpage < Formula
  desc "Aws pager masking privacy sensitive information"
  homepage "https://github.com/easytocloud/privpage"
  url "https://github.com/easytocloud/privpage/archive/refs/tags/v0.2.4.tar.gz"
  sha256 "77019487f8723ffe1105cb5c925301b8a9f50e7e2d6d595ed6ad9b80432bf96d"
  license "MIT"

  def install
    bin.install "distribution/bin/privpage"
bin.install "distribution/bin/whoiam"
  end
end
