# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class SsoTools < Formula
  desc "Sso tools for use in aws ec2 instances"
  homepage "https://github.com/easytocloud/sso-tools"
  url "https://github.com/easytocloud/sso-tools/archive/refs/tags/v0.3.1.tar.gz"
  sha256 "9154238bf3d36b3e1e8ba8a9bf6df6ebeee971fab242f94b3359070b1bc33cac"

  depends_on "easytocloud/tap/aws-utils"

  def install
    bin.install "distribution/bin/ssostart"
bin.install "distribution/bin/generate-sso-config"
  end
end
