# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class SsoTools < Formula
  desc "Sso tools for use in aws ec2 instances"
  homepage "https://github.com/easytocloud/sso-tools"
  url "https://github.com/easytocloud/sso-tools/archive/refs/tags/v0.7.6.tar.gz"
  sha256 "f7f7ede86a27e503179ff8978245a862106d8c6699b188233cedf8f1a5bfad04"

  depends_on "direnv"
  depends_on "easytocloud/tap/codecommit-utils"
  depends_on "jq"

  def install
    bin.install "distribution/bin/ssostart"
bin.install "distribution/bin/generate-sso-config"
zsh_completion.install "distribution/completions/_generate-sso-config"
  end
end
