# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Ssostart < Formula
  desc "Aws sso login helper with aws-envs awareness"
  homepage "https://github.com/easytocloud/ssostart"
  url "https://github.com/easytocloud/ssostart/archive/refs/tags/v1.1.0.tar.gz"
  sha256 "a1d37ae9230420db25d0cc90c68f62edc0373ee22cbe3dd45ec9a33c9deaf062"

  def install
    bin.install "distribution/bin/ssostart"
zsh_completion.install "distribution/completions/_ssostart"
  end
end
