# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Ssostart < Formula
  desc "Aws sso login helper with aws-envs awareness"
  homepage "https://github.com/easytocloud/ssostart"
  url "https://github.com/easytocloud/ssostart/archive/refs/tags/v1.0.2.tar.gz"
  sha256 "3a049e024d3748c0bc0e707418385b0df92127c5265b267cd24beef4a579e1de"

  def install
    bin.install "distribution/bin/ssostart"
zsh_completion.install "distribution/completions/_ssostart"
  end
end
