# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Ssostart < Formula
  desc "Aws sso login helper with aws-envs awareness"
  homepage "https://github.com/easytocloud/ssostart"
  url "https://github.com/easytocloud/ssostart/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "ad833724de51dcc8d2e962eb8370b9710c06a80d20ba1dd345beb7f5d54dfb8e"

  def install
    bin.install "distribution/bin/ssostart"
zsh_completion.install "distribution/completions/_ssostart"
  end
end
