# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class ZshFunctions < Formula
  desc "Common zsh functions"
  homepage "https://github.com/easytocloud/zsh_functions"
  url "https://github.com/easytocloud/zsh_functions/archive/v0.1.1.tar.gz"
  sha256 "669372b5d0ae5fdaca2ec369299be5b834476bf850680662b26b9ecaececf53c"
  license "MIT"

  depends_on "bash" => :build

  def install
    zsh_function.install "distribution/functions/_log"
zsh_function.install "distribution/functions/_error"
zsh_function.install "distribution/functions/_debug"
zsh_function.install "distribution/functions/_die"

system "./postinstall"
  end
end
