# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class ZshFunctions < Formula
  desc "Common zsh functions"
  homepage "https://github.com/easytocloud/zsh_functions"
  url "https://github.com/easytocloud/zsh_functions/archive/v0.1.2.tar.gz"
  sha256 "aaaa33b2acff1c4389666aa9e549f956e6d019ec8777550346e4ed2c5dac0ae7"
  license "MIT"

  depends_on "bash" => :build

  def install
    zsh_function.install "distribution/functions/_log"
zsh_function.install "distribution/functions/_error"
zsh_function.install "distribution/functions/_debug"
zsh_function.install "distribution/functions/_die"

system "./postinstall"
  end
end
