# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class ZshFunctions < Formula
  desc "Common zsh functions"
  homepage "https://github.com/easytocloud/zsh_functions"
  url "https://github.com/easytocloud/zsh_functions/archive/v0.1.3.tar.gz"
  sha256 "997858fad30662e4f4feca1f80317c57d353ce2463d6d562f45e8bf8262ceaf7"
  license "MIT"

  depends_on "bash" => :build

  def install
    zsh_function.install "distribution/functions/_log"
zsh_function.install "distribution/functions/_error"
zsh_function.install "distribution/functions/_debug"
zsh_function.install "distribution/functions/_die"

system "./postinstall"
  end
end
